"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, type Edge, type Node, type NodeProps } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { Activity, ArrowUpRight, BookOpen, Check, ChevronRight, CircleGauge, Clock3, Database, ExternalLink, Rss, FileText, Gauge, GitFork, History, LayoutDashboard, LoaderCircle, MessageSquareText, Play, RefreshCw, Search, ServerCog, Sparkles, ThumbsDown, ThumbsUp, Users } from "lucide-react";
import { toast, Toaster } from "sonner";
import { DEFAULT_SOURCES } from "@/lib/sources";
import type { BriefingRun, MissionEvent, RunHistoryItem } from "@/lib/types";

type View = "workflow" | "telemetry" | "grafana" | "history" | "index" | "admin";
type FlowData = { label: string; eyebrow: string; tone: string; detail: string };
const fmtTime = (iso: string) => new Intl.DateTimeFormat("en", { hour: "2-digit", minute: "2-digit", second: "2-digit" }).format(new Date(iso));

function FlowNode({ data }: NodeProps<Node<FlowData>>) {
  return <div className={`flow-node ${data.tone}`}><Handle type="target" position={Position.Left} /><span className="flow-eyebrow">{data.eyebrow}</span><strong>{data.label}</strong><small>{data.detail}</small><Handle type="source" position={Position.Right} /></div>;
}
const nodeTypes = { mission: FlowNode };

function makeGraph(run: BriefingRun | null): { nodes: Node<FlowData>[]; edges: Edge[] } {
  const active = run?.status === "running";
  const nodes: Node<FlowData>[] = [
    { id: "sources", type: "mission", position: { x: 0, y: 135 }, data: { eyebrow: "04 FEEDS", label: "Substack sources", detail: "metadata + fingerprints", tone: "cyan" } },
    { id: "scout", type: "mission", position: { x: 285, y: 38 }, data: { eyebrow: active ? "WORKING" : "COMPLETE", label: "Scout", detail: `${run?.newArticles ?? 0} new · ${run?.duplicates ?? 0} ignored`, tone: "violet" } },
    { id: "memory", type: "mission", position: { x: 285, y: 235 }, data: { eyebrow: "MEMORY", label: "Seen article index", detail: "URL · hash · title similarity", tone: "amber" } },
    { id: "curator", type: "mission", position: { x: 575, y: 70 }, data: { eyebrow: active ? "QUEUED" : "COMPLETE", label: "Curator", detail: `${run?.selected ?? 0} stories selected`, tone: "violet" } },
    { id: "writer", type: "mission", position: { x: 850, y: 70 }, data: { eyebrow: run ? "COMPLETE" : "IDLE", label: "Writer", detail: `${run?.outputTokens ?? 0} output tokens`, tone: "violet" } },
    { id: "quality", type: "mission", position: { x: 850, y: 245 }, data: { eyebrow: "SCORER", label: `${run?.qualityScore ?? "—"} quality`, detail: "grounded · novel · clear", tone: "green" } },
    { id: "review", type: "mission", position: { x: 1130, y: 135 }, data: { eyebrow: "HUMAN GATE", label: "Editorial review", detail: run?.status === "approved" ? "approved" : "awaiting feedback", tone: "rose" } },
  ];
  const edges: Edge[] = [["sources", "scout"], ["memory", "scout"], ["scout", "curator"], ["curator", "writer"], ["writer", "quality"], ["writer", "review"], ["quality", "review"], ["review", "memory"]].map(([source, target], i) => ({ id: `e${i}`, source, target, animated: active && i < 4, type: "smoothstep", style: { stroke: i === 7 ? "#d97706" : "#334155", strokeWidth: 1.6 } }));
  return { nodes, edges };
}

export function MissionControl() {
  const [view, setView] = useState<View>("workflow"); const [run, setRun] = useState<BriefingRun | null>(null); const [running, setRunning] = useState(false); const [selectedEvent, setSelectedEvent] = useState<MissionEvent | null>(null); const [draft, setDraft] = useState(""); const [feedback, setFeedback] = useState(""); const abortRef = useRef<AbortController | null>(null); const activeRunIdRef = useRef<string | null>(null);
  const [health, setHealth] = useState<{ supabaseConfigured: boolean; openaiConfigured: boolean; telemetryConfigured: boolean; model: string } | null>(null); const [model, setModel] = useState("gpt-6-luna"); const [models, setModels] = useState<string[]>([]);
  const load = useCallback(async () => { const [rr, hr] = await Promise.all([fetch("/api/runs", { cache: "no-store" }), fetch("/api/health", { cache: "no-store" })]); if (rr.ok) { const next = await rr.json() as BriefingRun; setRun(next); setDraft(next.markdown ?? ""); } if (hr.ok) setHealth(await hr.json() as { supabaseConfigured: boolean; openaiConfigured: boolean; telemetryConfigured: boolean; model: string }); }, []);
  useEffect(() => { load(); fetch("/api/models").then((r) => r.ok ? r.json() : null).then((value: unknown) => { const data = value as { configuredModel?: string; models?: string[] } | null; if (data?.configuredModel && data.models) { setModel(localStorage.getItem("mission-control-model") ?? data.configuredModel); setModels(data.models); } }).catch(() => undefined); }, [load]);
  const startRun = async () => { const controller = new AbortController(); const runId = crypto.randomUUID(); abortRef.current = controller; activeRunIdRef.current = runId; setRunning(true); setSelectedEvent(null); try { const response = await fetch("/api/runs", { method: "POST", signal: controller.signal, headers: { "x-mission-run-id": runId, "x-llm-model": model } }); const data = await response.json().catch(() => ({})) as BriefingRun & { error?: string }; if (!response.ok) throw new Error(data.error ?? `Run failed (${response.status})`); setRun(data); setDraft(data.markdown); toast.success("Briefing is ready for review"); } catch (error) { if (error instanceof DOMException && error.name === "AbortError") toast.message("Mission stopped"); else toast.error(error instanceof Error ? error.message : "Run failed"); } finally { abortRef.current = null; activeRunIdRef.current = null; setRunning(false); } };
  const stopRun = async () => { const runId = activeRunIdRef.current; abortRef.current?.abort(); if (runId) await fetch("/api/runs/cancel", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ runId }) }).catch(() => undefined); };
  const submitFeedback = async (verdict: "approved" | "rejected" | "edited") => { if (!run) return; try { const response = await fetch("/api/feedback", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ runId: run.id, verdict, rating: verdict === "approved" ? 5 : 2, note: feedback, markdown: draft }) }); const data = await response.json().catch(() => ({})) as { error?: string }; if (response.ok) { setRun({ ...run, status: verdict === "approved" ? "approved" : "review" }); toast.success(verdict === "approved" ? "Approved and added to editorial memory" : "Feedback saved for the next run"); } else toast.error(data.error ?? `Could not save feedback (${response.status})`); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not save feedback"); } };
  const graph = useMemo(() => makeGraph(run), [run]);
  const grafanaBase = process.env.NEXT_PUBLIC_GRAFANA_URL ?? "http://localhost:3001";
  const grafanaTrace = run ? `${grafanaBase}/explore?orgId=1&left=${encodeURIComponent(JSON.stringify({ datasource: "tempo", queries: [{ query: run.traceId, queryType: "traceql" }] }))}` : grafanaBase;

  return <><Toaster theme="dark" position="bottom-right" /><div className="app-shell"><aside className="rail"><div className="brand-mark"><GitFork size={19} /></div><nav aria-label="Primary navigation"><button className={view === "workflow" ? "active" : ""} onClick={() => setView("workflow")} aria-label="Workflow"><GitFork size={19} /></button><button className={view === "telemetry" ? "active" : ""} onClick={() => setView("telemetry")} aria-label="Telemetry"><Activity size={19} /></button><button className={view === "grafana" ? "active" : ""} onClick={() => setView("grafana")} aria-label="Grafana dashboards"><LayoutDashboard size={19} /></button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")} aria-label="Run history"><History size={19} /></button><button className={view === "index" ? "active" : ""} onClick={() => setView("index")} aria-label="Article index"><BookOpen size={19} /></button><button className={view === "admin" ? "active" : ""} onClick={() => setView("admin")} aria-label="Admin settings"><ServerCog size={19} /></button></nav><div className="rail-bottom"><button aria-label="Team"><Users size={19} /></button><div className="avatar">T</div></div></aside>
    <main><header className="topbar"><div><div className="crumb"><span>MISSIONS</span><ChevronRight size={13} /><strong>AI & data briefing</strong></div><h1>Agent Mission Control</h1></div><div className="top-actions"><span className={`health ${health?.openaiConfigured ? "ok" : "warn"}`}><i />{health?.openaiConfigured ? health.model : "Preview mode"}</span><button className="secondary" onClick={load}><RefreshCw size={15} /> Sync</button>{running && <button className="secondary" onClick={stopRun}>Stop</button>}<button className="run-button" onClick={startRun} disabled={running}>{running ? <LoaderCircle className="spin" size={16} /> : <Play size={15} fill="currentColor" />}{running ? "Running mission" : "Run briefing"}</button></div></header>
      <section className="mission-strip"><div><span className="pulse-dot" /><div><small>ACTIVE MISSION</small><strong>Monitor AI & data engineering</strong></div></div><dl><div><dt>Sources</dt><dd>4</dd></div><div><dt>New</dt><dd>{run?.newArticles ?? "—"}</dd></div><div><dt>Duplicates</dt><dd>{run?.duplicates ?? "—"}</dd></div><div><dt>Quality</dt><dd className="score">{run?.qualityScore ?? "—"}<small>/100</small></dd></div><div><dt>Est. cost</dt><dd>${run?.estimatedCostUsd?.toFixed(5) ?? "0.00000"}</dd></div></dl></section>
      <div className="workspace-tabs"><button className={view === "workflow" ? "active" : ""} onClick={() => setView("workflow")}>Agent workflow</button><button className={view === "telemetry" ? "active" : ""} onClick={() => setView("telemetry")}>Run telemetry</button><button className={view === "grafana" ? "active" : ""} onClick={() => setView("grafana")}>Grafana</button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")}>Run history</button><button className={view === "index" ? "active" : ""} onClick={() => setView("index")}>Source index</button><span>{run ? `RUN ${run.id.slice(0, 8).toUpperCase()}` : "NO RUN"}</span></div>
      {view === "workflow" && <section className="workflow-layout"><div className="graph-panel"><div className="panel-heading"><div><small>LIVE FLOW</small><h2>Communication map</h2></div><div className="legend"><span><i className="agent" />Agent</span><span><i className="memory" />Memory</span><span><i className="human" />Human</span></div></div><div className="flow-canvas"><ReactFlow nodes={graph.nodes} edges={graph.edges} nodeTypes={nodeTypes} fitView minZoom={0.55} maxZoom={1.65} attributionPosition="bottom-left"><Background color="#243047" gap={22} size={1} /><Controls showInteractive={false} /><MiniMap pannable zoomable nodeColor={(n) => (n.data as FlowData).tone === "violet" ? "#8b5cf6" : "#0891b2"} /></ReactFlow></div></div><aside className="event-panel"><div className="panel-heading"><div><small>EVENT STREAM</small><h2>Agent activity</h2></div><span className="live-label"><i />LIVE</span></div><div className="event-list">{run?.events?.slice().reverse().map((event) => <button key={event.id} onClick={() => setSelectedEvent(event)} className={selectedEvent?.id === event.id ? "selected" : ""}><span className="event-icon">{event.kind.includes("duplicate") ? <Database size={14} /> : event.kind.includes("quality") ? <Gauge size={14} /> : event.kind.includes("draft") ? <FileText size={14} /> : <MessageSquareText size={14} />}</span><div><strong>{event.actor} <ChevronRight size={11} /> {event.target}</strong><p>{event.message}</p><small>{fmtTime(event.createdAt)}{event.durationMs ? ` · ${(event.durationMs / 1000).toFixed(1)}s` : ""}{event.tokens != null ? ` · ${event.tokens} tok` : ""}</small></div></button>)}</div></aside></section>}
      {view === "telemetry" && <Telemetry run={run} grafanaTrace={grafanaTrace} health={health} />}{view === "grafana" && <GrafanaHub baseUrl={grafanaBase} />}{view === "history" && <RunHistory baseUrl={grafanaBase} onOpenRun={(item) => { setRun({ ...item, newArticles: 0, duplicates: 0, selected: 0, events: [] }); setDraft(item.markdown); setView("telemetry"); }} />}{view === "index" && <SourceIndex run={run} />}{view === "admin" && <AdminSettings model={model} models={models} onChange={(value) => { setModel(value); localStorage.setItem("mission-control-model", value); toast.success(`${value} selected for this browser`); }} />}
      <section className="review-panel"><div className="review-header"><div><small>OUTPUT ARTIFACT</small><h2>{run?.title ?? "AI & data engineering briefing"}</h2></div><div className="artifact-status"><span><Clock3 size={13} /> Awaiting review</span><span className="quality-pill"><CircleGauge size={14} /> {run?.qualityScore ?? "—"} quality</span></div></div><div className="editor-grid"><textarea value={draft} onChange={(e) => setDraft(e.target.value)} aria-label="Briefing markdown" /><div className="review-actions"><label>Editorial feedback<textarea value={feedback} onChange={(e) => setFeedback(e.target.value)} placeholder="What should the agents remember next time?" /></label><button className="approve" onClick={() => submitFeedback(draft !== run?.markdown ? "edited" : "approved")}><ThumbsUp size={15} />Approve & remember</button><button className="reject" onClick={() => submitFeedback("rejected")}><ThumbsDown size={15} />Request revision</button><a href={grafanaTrace} target="_blank" rel="noreferrer"><ExternalLink size={14} />Open linked trace</a></div></div></section>
    </main></div></>;
}

function Telemetry({ run, grafanaTrace, health }: { run: BriefingRun | null; grafanaTrace: string; health: { supabaseConfigured: boolean; openaiConfigured: boolean; telemetryConfigured: boolean; model: string } | null }) {
  const spans = run?.events.filter((e) => e.durationMs) ?? []; const max = Math.max(1, ...spans.map((s) => s.durationMs ?? 0));
  return <section className="telemetry-view"><div className="telemetry-cards"><article><span><Activity size={16} /> RUN LATENCY</span><strong>{(spans.reduce((n, e) => n + (e.durationMs ?? 0), 0) / 1000).toFixed(1)}s</strong><small>end-to-end agent work</small></article><article><span><Sparkles size={16} /> TOKENS</span><strong>{((run?.inputTokens ?? 0) + (run?.outputTokens ?? 0)).toLocaleString()}</strong><small>{run?.inputTokens ?? 0} in · {run?.outputTokens ?? 0} out</small></article><article><span><Gauge size={16} /> QUALITY</span><strong>{run?.qualityScore ?? "—"}<em>/100</em></strong><small>deterministic rubric</small></article><article><span><ServerCog size={16} /> EXPORT</span><strong className={health?.telemetryConfigured ? "good" : "muted"}>{health?.telemetryConfigured ? "OTLP" : "OFF"}</strong><small>Alloy → LGTM</small></article></div><div className="trace-card"><div className="panel-heading"><div><small>DISTRIBUTED TRACE</small><h2>LLM call waterfall</h2></div><a href={grafanaTrace} target="_blank" rel="noreferrer">Explore in Grafana <ArrowUpRight size={14} /></a></div><div className="waterfall"><div className="trace-row root"><span>mission.run</span><div><i style={{ width: "100%" }} /></div><small>{run?.traceId.slice(0, 12) ?? "no trace"}</small></div>{spans.map((span, i) => <div className="trace-row" key={span.id}><span>{span.kind.replaceAll(".", " / ")}</span><div><i style={{ marginLeft: `${i * 9}%`, width: `${Math.max(9, ((span.durationMs ?? 0) / max) * 68)}%` }} /></div><small>{((span.durationMs ?? 0) / 1000).toFixed(2)}s</small></div>)}</div></div><div className="signal-grid"><div><h3><Activity size={15} /> Tempo traces</h3><p>Mission, ingestion, curator and writer spans linked by trace ID.</p></div><div><h3><Search size={15} /> Loki logs</h3><p>Structured lifecycle and error events with run correlation.</p></div><div><h3><CircleGauge size={15} /> Mimir metrics</h3><p>Run volume, tokens, quality, errors and latency trends.</p></div></div></section>;
}

function GrafanaHub({ baseUrl }: { baseUrl: string }) {
  const dashboards = [
    { id: "overview", label: "LLM operations", uid: "agent-mission-control", slug: "agent-mission-control-e28094-llm-operations" },
    { id: "traces", label: "Tracing", uid: "agent-traces", slug: "agent-traces" },
    { id: "logs", label: "Logs", uid: "agent-logs", slug: "agent-logs" },
    { id: "metrics", label: "Metrics", uid: "agent-metrics", slug: "agent-metrics" },
  ];
  const [active, setActive] = useState(dashboards[0]);
  const src = `${baseUrl}/d/${active.uid}/${active.slug}?orgId=1&from=now-6h&to=now&refresh=15s&kiosk`;
  return <section className="grafana-view"><div className="grafana-toolbar"><div><small>EMBEDDED OBSERVABILITY</small><h2>Grafana dashboards</h2></div><div className="grafana-tabs">{dashboards.map((dashboard) => <button key={dashboard.id} className={active.id === dashboard.id ? "active" : ""} onClick={() => setActive(dashboard)}>{dashboard.label}</button>)}</div><a href={src.replace("&kiosk", "")} target="_blank" rel="noreferrer">Open full screen <ArrowUpRight size={14} /></a></div><div className="grafana-frame"><iframe title={`Grafana ${active.label}`} src={src} loading="lazy" /></div></section>;
}

function RunHistory({ baseUrl, onOpenRun }: { baseUrl: string; onOpenRun: (run: RunHistoryItem) => void }) {
  const [runs, setRuns] = useState<RunHistoryItem[]>([]);
  const [selected, setSelected] = useState<RunHistoryItem | null>(null);
  useEffect(() => { fetch("/api/history", { cache: "no-store" }).then((response) => response.ok ? response.json() : []).then((value) => { const items = value as RunHistoryItem[]; setRuns(items); setSelected(items[0] ?? null); }); }, []);
  return <section className="history-view"><div className="history-list"><div className="history-title"><div><small>AGENT MEMORY</small><h2>Run history</h2></div><span>{runs.length} runs</span></div>{runs.map((item) => <button key={item.id} className={selected?.id === item.id ? "selected" : ""} onClick={() => setSelected(item)}><span className={`run-state ${item.status}`} /><div><strong>{item.title}</strong><p>{new Date(item.startedAt).toLocaleString()}</p></div><div className="history-score"><b>{item.qualityScore}</b><small>quality</small></div></button>)}</div><div className="history-detail">{selected ? <><div className="history-detail-head"><div><span className={`verdict ${selected.status}`}>{selected.feedbackVerdict ?? selected.status}</span><h2>{selected.title}</h2><p>Run {selected.id.slice(0, 8)} · trace {selected.traceId.slice(0, 12)}</p></div><div className="history-actions"><button onClick={() => onOpenRun(selected)}>Inspect run</button><a href={`${baseUrl}/explore?orgId=1&left=${encodeURIComponent(JSON.stringify({ datasource: "tempo", queries: [{ query: selected.traceId, queryType: "traceql" }] }))}`} target="_blank" rel="noreferrer">Trace <ExternalLink size={13} /></a></div></div><dl className="history-metrics"><div><dt>Quality</dt><dd>{selected.qualityScore}/100</dd></div><div><dt>Tokens</dt><dd>{(selected.inputTokens + selected.outputTokens).toLocaleString()}</dd></div><div><dt>Cost</dt><dd>${selected.estimatedCostUsd.toFixed(5)}</dd></div><div><dt>Decision</dt><dd>{selected.feedbackVerdict ?? "pending"}</dd></div></dl><pre>{selected.markdown}</pre></> : <div className="empty-history">No runs yet. Start a briefing to create the first record.</div>}</div></section>;
}

function SourceIndex({ run }: { run: BriefingRun | null }) {
  return <section className="index-view"><div className="index-toolbar"><div><small>SOURCE MEMORY</small><h2>Indexed publications</h2></div><div className="search-box"><Search size={15} /><input placeholder="Search metadata" aria-label="Search indexed metadata" /></div></div><div className="source-table"><div className="table-row head"><span>Publication</span><span>Endpoint</span><span>Last run</span><span>State</span><span /></div>{DEFAULT_SOURCES.map((source, i) => <div className="table-row" key={source.id}><span><i className={`source-glyph g${i}`}><Rss size={15} /></i><strong>{source.name}</strong></span><span className="mono">{source.feedUrl}</span><span>{run ? fmtTime(run.startedAt) : "Never"}</span><span><b className="indexed"><Check size={12} /> Indexed</b></span><a href={source.url} target="_blank" rel="noreferrer" aria-label={`Open ${source.name}`}><ExternalLink size={14} /></a></div>)}</div><div className="dedup-card"><Database size={18} /><div><strong>Three-layer duplicate protection</strong><p>Canonical URL → content fingerprint → normalized-title similarity. Previously seen metadata is rejected before any LLM call.</p></div><span>{run?.duplicates ?? 0} blocked</span></div></section>;
}

function AdminSettings({ model, models, onChange }: { model: string; models: string[]; onChange: (model: string) => void }) {
  return <section className="history-view"><div className="history-detail"><div className="history-detail-head"><div><small>ADMINISTRATION</small><h2>LLM runtime settings</h2><p>Model selection is stored only in this browser. Credentials remain in the server environment.</p></div></div><div className="editor-grid"><label>Provider<select value="openai" disabled><option>OpenAI / OpenAI-compatible</option></select></label><label>Model<select value={model} onChange={(e) => onChange(e.target.value)}>{models.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div><p className="muted">For an OpenAI-compatible gateway, set <code>OPENAI_BASE_URL</code> and <code>OPENAI_API_KEY</code> in <code>.env.local</code>, then restart the backend. Add the gateway's compatible model ID here by changing the environment or extending the preset list.</p></div></section>;
}
